spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

  datasource:
    url: jdbc:mysql://rm-bp12e7gy6am118rnpao.mysql.rds.aliyuncs.com:3306/flowersshopping
    username: flowers
    password: FlowersShopping123456
  data:
    redis:
      port: 6379
      host: localhost
      database: 0
  mail:
    host: smtp.qq.com
    port: 587
    username: 497101243@qq.com
    password: wvjsvbsyqshsbgjb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

pagehelper:
  reasonable: true
  helperDialect: mysql

logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug


